### PR TITLE
[feat/jobCards]- jobCard for employee

### LINKED ISSUE #15: [Feat] Job Component for Employee
A component that will provide job details at a glance for employee user.

### PR DESCRIPTION
**Pull request by shresthapr**
Screen Shot 2021-04-01 at 2 51 35 PM
Screen Shot 2021-04-01 at 2 52 18 PM
//responsive design added-- latest snapshot
Screen Shot 2021-04-05 at 8 12 21 PM

### CODE REVIEW

**Review by Alabbey2 — DISMISSED** [review]
all done

**Review by Chiranjibichapagain — CHANGES_REQUESTED** [review]
Looks good. Please try with making the company profile bigger and the icons don't look that aligned. Should we try with a different icon than a bigger and smaller heart?

**Review by SaharPerveen — CHANGES_REQUESTED** [review]
1. two hearts doesnt seem appropriate at all.. super like icon should be different then the heart.

**Comment by shresthapr** [comment]
> Looks good. Please try with making the company profile bigger and the icons don't look that aligned. Should we try with a different icon than a bigger and smaller heart?

-was  not sure which icons to use.  That is why added the big heart. It will/must be changed for sure.

**Comment by shresthapr** [comment]
> 1. two hearts doesnt seem appropriate at all.. super like icon should be different then the heart.
agree. That was a mere placeholder. :)

**Comment by shresthapr** [comment]
Insert the following to test the card
when user  ="employee" it renders employee component only, when it's applicant it renders applicant only.
Note. only props related to usertype are passed in real application. I have passed all the props for testing purpose only.
 <JobCard
        user="applicant"
        jobtitle="Head of department"
        company="Business College Helsinki"
        deadline="04.04.2021"
        location="Helsinki Finland"
        type="Full-time"
        level="junior"
        skills="React ,Nodejs, TypeScript, AWS, Python, and everything that has to be known"
        applicantName="Mr Smith"
        applicantTitle="Student"
        applicantLevel="Mid-Senior"
        applicantType="part-time, Full-time"
        applicantSkills="Nothing interesting or worth mentioning"
        applicantLocation="Davos Switzerland"
        availability="03.04.2030"
      />

**Review by Chiranjibichapagain — DISMISSED** [review]
Good Work!

**Review by SaharPerveen — DISMISSED** [review]

**Review by Alabbey2 — DISMISSED** [review]

**Pull request merged**
